# Generated by Django 4.2.15 on 2024-09-07 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
                ('accept_date', models.DateTimeField()),
                ('approximate_date', models.DateTimeField(null=True)),
                ('job_status', models.SmallIntegerField(default=-1)),
                ('closing_status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_date', models.DateTimeField()),
                ('frame_time', models.DurationField(default=0)),
                ('description', models.TextField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasks')),
            ],
        ),
    ]
