# Generated by Django 4.2.15 on 2024-08-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_product_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
