# Generated by Django 4.2.15 on 2024-08-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_remove_product_company_delete_company_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('job_acceptance_date', models.DateTimeField()),
                ('approximate_date', models.DateTimeField(null=True)),
                ('date_task', models.DateTimeField(null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.statustask')),
            ],
        ),
        migrations.CreateModel(
            name='PartTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_date', models.DateTimeField()),
                ('frame_time', models.DurationField(default=0)),
                ('description', models.TextField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasks')),
            ],
        ),
    ]
