# Generated by Django 4.2.15 on 2024-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date_task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='execution_period',
            field=models.DurationField(default=0),
        ),
    ]
