# Generated by Django 4.2.15 on 2024-09-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tasksjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasksJob',
        ),
    ]
