# Generated by Django 4.2.15 on 2024-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_tasksjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressjob',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='progressjob',
            name='frame_time',
            field=models.DurationField(null=True),
        ),
    ]
