# Generated by Django 4.2.15 on 2024-09-05 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tasks_date_task_tasks_execution_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='execution_period',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
